sudo: required
services:
  - docker

env:
  - CC="clang" OS="Gentoo" BUILD_FLAGS="--with-gtk3 --with-libnotify"
  - CC="clang" OS="Gentoo" BUILD_FLAGS="--with-gtk3 --without-libnotify"
  - CC="clang" OS="Gentoo" BUILD_FLAGS="--without-gtk3 --with-libnotify"
  - CC="clang" OS="Gentoo" BUILD_FLAGS="--without-gtk3 --without-libnotify"
  - CC="gcc" OS="Gentoo" BUILD_FLAGS="--with-gtk3 --with-libnotify"
  - CC="gcc" OS="Gentoo" BUILD_FLAGS="--with-gtk3 --without-libnotify"
  - CC="gcc" OS="Gentoo" BUILD_FLAGS="--without-gtk3 --with-libnotify"
  - CC="gcc" OS="Gentoo" BUILD_FLAGS="--without-gtk3 --without-libnotify"
  - CC="clang" OS="Debian" BUILD_FLAGS="--with-gtk3 --with-libnotify"
  - CC="clang" OS="Debian" BUILD_FLAGS="--with-gtk3 --without-libnotify"
  - CC="clang" OS="Debian" BUILD_FLAGS="--without-gtk3 --with-libnotify"
  - CC="clang" OS="Debian" BUILD_FLAGS="--without-gtk3 --without-libnotify"
  - CC="gcc" OS="Debian" BUILD_FLAGS="--with-gtk3 --with-libnotify"
  - CC="gcc" OS="Debian" BUILD_FLAGS="--with-gtk3 --without-libnotify"
  - CC="gcc" OS="Debian" BUILD_FLAGS="--without-gtk3 --with-libnotify"
  - CC="gcc" OS="Debian" BUILD_FLAGS="--without-gtk3 --without-libnotify"

before_install: ./.travis/before_install.sh

install: ./.travis/install.sh

script: ./.travis/script.sh
